"""Write Shared/FallbackBlocks.swift: the 0843 number blocks Ofcom lists as Allocated.

Used only by the on-device fallback (FALLBACK_0843=1 in scripts/create_project.py), for when
the server lookup can't run. Each Ofcom block is 10,000 numbers, e.g. "8430 12" covers
0843 012 0000 to 0843 012 9999. Allocated-only keeps the list at 5.67 million numbers,
which fits three Call Directory parts under the observed two-million limit.

Usage: fallback_0843_blocks.py [S8_CSV]   (default: download Ofcom's current s8.csv)
"""
import csv
import io
import sys
import urllib.request
from datetime import date
from pathlib import Path

S8_URL = ("https://www.ofcom.org.uk/siteassets/resources/documents/phones-telecoms-and-internet/"
          "information-for-industry/numbering/regular-updates/telephone-numbers/s8.csv")
root = Path(__file__).resolve().parent.parent

text = Path(sys.argv[1]).read_text() if len(sys.argv) > 1 else urllib.request.urlopen(S8_URL).read().decode()
# Columns: number block, block status, provider, number length, allocation date.
# The first header cell reads "NMS Number Block: Number Block", so columns are read by position.
rows = list(csv.reader(io.StringIO(text.lstrip("\ufeff"))))[1:]
blocks = sorted({
    int("44" + row[0].replace(" ", "") + "0000")
    for row in rows
    if row and row[0].replace(" ", "").startswith("843") and row[1] == "Allocated"
})
if any(len(str(start)) != 12 for start in blocks):
    sys.exit("unexpected block length; Ofcom file format changed")
lines = ",\n".join("        " + ", ".join(str(b) for b in blocks[i:i + 6]) for i in range(0, len(blocks), 6))
(root / "Shared/FallbackBlocks.swift").write_text(f"""// Generated by scripts/fallback_0843_blocks.py from Ofcom's S8 numbering file on {date.today().isoformat()}.
// The first number of every 0843 block Ofcom lists as Allocated; each block is 10,000 numbers.
enum FallbackBlocks {{
    static let allocated0843: [Int64] = [
{lines},
    ]
}}
""")
print(f"{len(blocks)} allocated 0843 blocks, {len(blocks) * 10_000:,} numbers")
